from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_PATH = ROOT / "data" / "snow-template.json"
OUTPUT_PATH = ROOT / "js" / "snow-data.js"


def to_javascript_module(payload: dict) -> str:
    meta = json.dumps(
        {
            "generatedAt": payload["generatedAt"],
            "provider": payload["provider"],
            "historicalMethod": payload["historicalMethod"],
            "historyWindow": payload["historyWindow"],
        },
        indent=2,
        ensure_ascii=True,
    )
    snow_snapshot = json.dumps(payload["resorts"], indent=2, ensure_ascii=True)

    return (
        "// This file is generated by scripts/generate-snow-data.py\n"
        "// It is safe to commit because the app is static-hosted.\n\n"
        f"export const snowSnapshotMeta = {meta};\n\n"
        f"export const snowSnapshot = {snow_snapshot};\n"
    )


def main() -> None:
    payload = json.loads(TEMPLATE_PATH.read_text(encoding="utf-8"))
    OUTPUT_PATH.write_text(to_javascript_module(payload), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
